name: "Tester"
description: "Test a nixos implementation"
author: "Emory Merryman"
inputs:
  defect:
    required: false
    description: The expected defect to find.  Since we either expect zero or one defect, this should either be blank or have one item in it.
    default: YES-DEFAULT
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/check.sh "${{ defect }}"
      shell: bash