name: "Test"
on:
  push:
jobs:
  pwd:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd $( mktemp --directory ) && git init && nix flake init && sed -e "s#\${IMPLEMENTATION}##" -e "s#\${TEST}##" -e "wflake.nix"
