name: "Test"
on:
  push:
jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd $( mktemp --directory ) && git init && nix flake init && sed -e "s#\${IMPLEMENTATION}#github:nextmoose/tester-test#" -e "s#\${TEST}#github:nextmoose/tester-test#" -e "wflake.nix"
