name: "Test"
on:
  push:
jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd $( mktemp --directory ) && git init && git config user.name "No User" && git config user.email "noone@nothing" && echo 1 && nix flake init && echo 2 && sed -e "s#\${IMPLEMENTATION}#github:nextmoose/tester#" -e "s#\${TEST}#github:nextmoose/tester-test#" -e "wflake.nix" && git commit --all --allow-empty-message --message "" && cat flake.nix && nix develop --command check ""
