name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      FOOBAR_A: one
      FOOBAR_B: two
      FOOBAR_C: three
    steps:
      - uses: nextmoose/tester@391f9b8e4f5e74cc37381418b4bfd9977a8d240d
        implementation-url: github:nextmoose/tester
	implementation-postulant: false
	test-url: github:nextmoose/tester-test
	test-postulant: false
	test-rev:
	defect:
	postulent: true
	token:
