name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      IMPLEMENTATION_URL: github:nextmoose/tester
      IMPLEMENTATION_POSTULATE: false
      TEST_URL: github:nextmoose/tester-test
      TEST_POSTULATE: false
      TEST_REV:
      DEFECT:
      POSTULATE: false
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: nextmoose/tester@761b4be06bf18abd6d3a213d460b1959618982ed
        with:
          implementation-url: $IMPLEMENTATION_URL
          implementation-postulate: $IMPLEMENTATION_POSTULATE
          test-url: $TEST_URL
          test-postulate: $TEST_POSTULATE
          test-rev: $TEST_REV
          defect: $DEFECT
          postulate: $POSTULATE
          token: $TOKEN
