name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - uses: nextmoose/test-action@83aedfe46b23254f924b5f2fee216af3ea0bc333
        with:
          implementation-url: github:nextmoose/tester
          implementation-postulate: false
          test-url: github:nextmoose/tester-test
          test-postulate: false
          test-rev: 
          test-defect: 
          postulate: false
