name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      IMPLEMENTATION_URL: github:nextmoose/tester
      IMPLEMENTATION_POSTULATE: false
      TEST_URL: github:nextmoose/tester-test
      TEST_POSTULATE: false
      TEST_REV:
      DEFECT:
      POSTULATE: false
      TOKEN: ${{ token }}
    steps:
      - uses: nextmoose/tester@5dbd4e9623681f2edacb05b195e9d2c7237af5c3
        with:
	  implementation-url: $IMPLEMENTATION_URL
	  implementation-postulate: $IMPLEMENTATION_POSTULATE
	  test-url: $TEST_URL
	  test-postulate: $TEST_POSTULATE
	  test-rev: $TEST_REV
	  defect: $DEFECT
	  postulate: $POSTULATE
          token: $TOKEN
