name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: nextmoose/tester@e0a78ec305de1a8e980cd88930f8d74e7cf67e0d
        with:
          implementation-url: github:nextmoose/tester
          implementation-postulate: false
          test-url: github:nextmoose/tester-test
          test-postulate: false
          test-rev: 
          defect: 
          postulate: false
          token: ${{ secrets.TOKEN }}
