name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      FOOBAR_A: one
      FOOBAR_B: two
      FOOBAR_C: three
    steps:
      - uses: nextmoose/tester@07bd66efe6026fdf938492a161c4060e4c285de0
