name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      FOOBAR_A: one
      FOOBAR_B: two
      FOOBAR_C: three
    steps:
      - uses: nextmoose/tester@20bcebffaf23f135282706607f0203ac749db31b
        with:
          defect: $FOOBAR_A
