name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - uses: nextmoose/test-action@7a132fb0cca27840a0c8822de6d990ca511d3e0c
        with:
          implementation-url: github:nextmoose/tester
          implementation-postulate: false
          test-url: github:nextmoose/tester-test
          test-postulate: false
          test-rev: 
          test-defect: BAD
          postulate: true
