name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      FOOBAR_A: one
      FOOBAR_B: two
      FOOBAR_C: three
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          packages: nix,cowsay,mktemp
          script: cowsay MOO $FOOBAR_A $FOOBAR_B $FOOBAR_C &&
       - used: workflow/nix-shell-action@v3
         with: cd $( mktemp -d ) && nix flake init && echo '{ inputs = { flake-utils.url = "github:numtide/flake-utils?rev=5aed5285a952e0b949eb3ba02c12fa4fcfef535f" ; nixpkgs.url = "github:nixos/nixpkgs?rev=57eac89459226f3ec743ffa6bbbc1042f5836843" ; } ; outputs = { flake-utils , nixpkgs , self } : flake-utils.lib.eachDefaultSystem ( system : let pkgs = builtins.getAttr system nixpkgs.legacyPackages ; in pkgs.mkShell { buildInputs = [ ( pkgs.writeShellScriptBin "foobar" "${ pkgs.coreutils }/bin/env" ) ] ; } ; ) ; }' > flake.nix && nix develop 