name: "experiment"
on:
  push:
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: nixpkgs#docker
          script: |
	    docker --help