on:
  push: 
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: nix-shell .github/workflows/branch/shell.nix --argstr expected "^init/.*$"
          --command branch
  check:
    needs:
      - branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: nix-shell .github/workflows/check/shell.nix --arg implementation-home
          true --arg tester-home true --command check
  post-check:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          extra_nix_config: access-tokens = github.com = ${{ secrets.TOKEN }}
        uses: cachix/install-nix-action@v17
      - run: nix-shell .github/workflows/post-check/shell.nix --command post-check
name: test
