name: test
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: if [ -f flake.lock ]; then ! cat flake.lock | jq --raw-output "$( cat
          .github/workflows/versions.txt )" --exit-status ; fi
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-actions@v17
      - run: cd .github/workflows/pre-check && nix develop --command check
  check:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-actions@v17
      - run: cd .github/workflows/check && nix develop --command check
on:
  push: 
